name: Windows Build Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Download QR Code Generator Dependencies
      run: |
        echo "Downloading QrCodeGen library..."
        curl -o qrcodegen.hpp https://raw.githubusercontent.com/nayuki/QR-Code-generator/master/cpp/qrcodegen.hpp
        curl -o qrcodegen.cpp https://raw.githubusercontent.com/nayuki/QR-Code-generator/master/cpp/qrcodegen.cpp
        echo "✅ Dependencies downloaded"
      shell: cmd
      
    - name: Check C++ Syntax (Windows)
      run: |
        echo "Checking cli_args_debugger.cpp..."
        cl /EHsc /std:c++20 /permissive- /Zc:__cplusplus /c /W4 /WX cli_args_debugger.cpp
        echo "Checking seh_wrapper.cpp..."
        cl /EHsc /std:c++20 /permissive- /Zc:__cplusplus /c /W4 /WX seh_wrapper.cpp
        echo "✅ Windows compilation check passed"
      shell: cmd

