name: Cross-Platform Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Download QR Code Generator Dependencies
      run: |
        echo "Downloading QrCodeGen library..."
        curl -o qrcodegen.hpp https://raw.githubusercontent.com/nayuki/QR-Code-generator/master/cpp/qrcodegen.hpp
        curl -o qrcodegen.cpp https://raw.githubusercontent.com/nayuki/QR-Code-generator/master/cpp/qrcodegen.cpp
        echo "✅ Dependencies downloaded"
      shell: cmd
      
    - name: Check C++ Syntax (Windows)
      run: |
        echo "Checking cli_args_debugger.cpp..."
        cl /EHsc /std:c++20 /permissive- /Zc:__cplusplus /c /W4 /WX cli_args_debugger.cpp
        echo "Checking seh_wrapper.cpp..."
        cl /EHsc /std:c++20 /permissive- /Zc:__cplusplus /c /W4 /WX seh_wrapper.cpp
        echo "✅ Windows compilation check passed"
      shell: cmd

  macos-validation:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install LLVM
      run: |
        brew install llvm
        echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
        
    - name: Check C++ Syntax (macOS)
      run: |
        # Note: This is Windows-specific code, so we only check for basic syntax issues
        # Use our custom validation script that handles missing Windows headers
        chmod +x validate.sh
        ./validate.sh
    
    - name: Check formatting
      run: |
        # Skip clang-format on Windows-specific code
        echo "⚠️ Skipping clang-format on Windows-specific DirectX code"
        echo "   Format checking should be done on Windows with proper DirectX SDK"
        
    - name: Run static analysis
      run: |
        brew install cppcheck
        # Run basic checks on test files only (they don't require Windows headers)
        echo "🔍 Running cppcheck on test files..."
        cppcheck --enable=warning,style,performance,portability --std=c++20 \
          --suppress=missingIncludeSystem tests/*.cpp || echo "⚠️ Some checks failed (expected for cross-platform analysis)"